### PR TITLE
Added script for hashing files

### PR DESCRIPTION
**Pull request by harshareddy794**
Issue no #12 
Please review my PR

### CODE REVIEW

**Review by tejan-singh — CHANGES_REQUESTED** [review]
Please add an example/use case how to use this script in readme file.

**Comment by harshareddy794** [comment]
I have done changes. can you check @tejan-singh

**Comment by SANKET7738** [comment]
add an image of the output/demo. @harshareddy794

**Comment by harshareddy794** [comment]
Changes are done @SANKET7738

**Comment by harshareddy794** [comment]
Thank you @SANKET7738  and @tejan-singh

**Pull request merged**
