### PR TITLE
Network Usage Notifier

### PR DESCRIPTION
**Pull request by Nibba2018**
Parent issue: #98 

### Type of change

**Select all that applies**:
* [X] New feature (non-breaking change which adds functionality)

### Checklist:

* [X] My code follows the style guidelines(Clean Code) of this project.
* [X] I have performed a self-review of my own code.
* [X] I have used consistent code conventions and clear function/method/variable names.
* [X] I have commented on my code, particularly in hard-to-understand areas.
* [X] I have created a helpful and easy to understand README.md which contains description, requirements and use case.
* [X] I have added relevent screenshots if necessary.
* [X] I have added my work in respective language folder.
* [X] My changes generate no new warnings.

### CODE REVIEW

**Review by tejan-singh — CHANGES_REQUESTED** [review]
please add all your images to a seperate folder.

**Review by tejan-singh — CHANGES_REQUESTED** [review]
Capture

Also, suggest a fix for this.

**Comment by Nibba2018** [comment]
@tejan-singh , Well for windows [dbus-python-windows](https://github.com/uglide/dbus-python-windows/releases) should be installed or built manually from [here](https://github.com/uglide/dbus-python-windows)

Or, visual studio build tools should be installed.

**Comment by Nibba2018** [comment]
@tejan-singh , Could you check if it runs without installing dbus-python on windows?

**Comment by tejan-singh** [comment]
No. It requires dbus module for windows. Please update your readme for Windows users.

**Comment by Nibba2018** [comment]
@tejan-singh I have written extra code for windows.

**Review by tejan-singh — CHANGES_REQUESTED** [review]
Capture1

Still an error.

**Comment by tejan-singh** [comment]
You can do one thing. Make this script for Linux only. Open another issue for running this script on windows and start working.

**Comment by Nibba2018** [comment]
@tejan-singh , I have made the script cross-platform, all you have to do is:
first run `python install.py`
then run `python app.py` this will run irrespective of the operating system.

**Comment by Nibba2018** [comment]
@tejan-singh Can you tell me what the output is for `sys.platform` in your system?

**Comment by tejan-singh** [comment]
Yes, I know that but your install.py is also having an error. Check this out.

Capture3

**Comment by Nibba2018** [comment]
@tejan-singh Okay I know what the problem is, the script is not detecting the os correctly. I am fixing it in a second.

**Comment by Nibba2018** [comment]
@tejan-singh Now it should work.

**Comment by tejan-singh** [comment]
Yes, its working fine now. Please next time run all the checks on both Linux and windows before sending PRs.

**Pull request merged**
