### PR TITLE
Human detection 

### PR DESCRIPTION
**Pull request by TaniaMalhotra**
### Your checklist for this pull request
:warning: Please review the [guidelines for contributing](https://github.com/sanscript-tech/hacking-tools-scripts/blob/main/CONTRIBUTING.md) to this repository.

Parent issue: #105

### Type of change

**Select all that applies**:
* [X] New feature (non-breaking change which adds functionality)
* [X] Bug fix (non-breaking change which fixes an issue)
* [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
* [ ] This change requires a documentation update

### Checklist:

* [X] My code follows the style guidelines(Clean Code) of this project.
* [X] I have performed a self-review of my own code.
* [X] I have used consistent code conventions and clear function/method/variable names.
* [X] I have commented on my code, particularly in hard-to-understand areas.
* [X] I have created a helpful and easy to understand README.md which contains description, requirements and use case.
* [X] I have added relevent screenshots if necessary.
* [X] I have added my work in respective language folder.
* [X] My changes generate no new warnings.

### CODE REVIEW

**Review by tejan-singh — CHANGES_REQUESTED** [review]
Please take input image through command line.

**Comment by TaniaMalhotra** [comment]
Okay!
I've updated the PR with changes

**Comment by tejan-singh** [comment]
Nice work!

**Comment by TaniaMalhotra** [comment]
@tejan-singh 
Can I take it a level up and make an issue for human detection from videos?

> I plan to do this by extracting individual frames from the video

**Pull request merged**
