### PR TITLE
Pdf to Image script using Python.

### PR DESCRIPTION
**Pull request by hrj-star**
Added Pdf to Image script in python , output,commands , demo screenshots , README.md file.

### CODE REVIEW

**Comment by tejan-singh** [comment]
are you a participant? we are assigning issues only to participants.

**Comment by hrj-star** [comment]
Yes , I am , I have participated for this open source project and have registered through that form .

**Comment by hrj-star** [comment]
I have followed whats written in contributing rules , that we can register as participant and then contribute , It isnt mentioned anywhere that issues will be assigned first , then need to work on that . Please correct me if I am mistaken. Thanks !

**Comment by tejan-singh** [comment]
Please go through contribution guidelines #130

**Comment by hrj-star** [comment]
Okay , went through the guidelines . 
Can I create a new  issue on the topic ?

**Comment by tejan-singh** [comment]
@hrj-star yes you can but Have you joined the slack channel? Also, I need to know your full name to confirm your participation.

**Comment by hrj-star** [comment]
I have filled Google Form for registration yesterday - Het Rakesh Joshi , but havent received any confirmation mail which would include the slack channel joining link .

**Comment by tejan-singh** [comment]
please mail your issues.

**Pull request closed without merging**
