### PR TITLE
Added the code for image converter to JPG having issue #100

### PR DESCRIPTION
**Pull request by Tejas1510**
I have the code for image converter to JPG having issue #100 where I have used Tkinter library for frontend part while entire code has been built with python and pillow Library

### CODE REVIEW

**Comment by SANKET7738** [comment]
too many commits. squash them then make a PR.

**Comment by Tejas1510** [comment]
@SANKET7738 Sir I searched on the internet but am unable to squash all commits 
Can you please help me with that

**Comment by SANKET7738** [comment]
just google how to use the git squash command.you will find many relevant videos and tutorials, if you still get stuck somewhere message me on slack.

**Comment by Tejas1510** [comment]
Sure Sir

**Pull request closed without merging**
