### PR TITLE
Added script for primality test in c++

### PR DESCRIPTION
**Pull request by ultraUnicorn74**

### CODE REVIEW

**Review by yashaswibiyahut — CHANGES_REQUESTED** [review]
@richabh456  Please add readme file with sample Input Output and complexity

**Comment by ultraUnicorn74** [comment]
@yashaswibiyahut please review my pr .

**Comment by yashaswibiyahut** [comment]
@richabh456 Please add proper comments and input messages in your code. 
And also add space complexity.
Rest LGTM.

**Comment by ultraUnicorn74** [comment]
@yashaswibiyahut i have done the required changes ma'am. please suggest if any other changes are required.

**Comment by yashaswibiyahut** [comment]
@richabh456 kindly add input messages also so that user can understand which input has to take.
Ex-In line 17 before taking the input for test cases:
Give an input message to the user: "Enter the number of test cases"
Hope you understand.
Thanks!

**Comment by ultraUnicorn74** [comment]
@yashaswibiyahut Thank you for your suggestion ma'am. i have made changes.

**Review by yashaswibiyahut — APPROVED** [review]

**Pull request merged**
