### PR TITLE
Added a web crawler for grabbing links from a website #61

### PR DESCRIPTION
**Pull request by Tejas1510**
I have added a web crawler for grabbing links from a website and is built in python
I am attaching a sample screenshot of how the output looks likes

output

### CODE REVIEW

**Comment by SANKET7738** [comment]
Please update the repo as it has been restructured. Please add your work in the respective language folder and also it is showing that you are working directly on the master which is not acceptable. please make a separate branch and do the required changes.

**Comment by Tejas1510** [comment]
@SANKET7738 sir Thank you for your guidance 
I will surely do the changes and raise a PR soon

**Comment by Tejas1510** [comment]
@SANKET7738 can you please help 
when i am forking the repository it is showing the old structure only
How to get the recent structure

**Comment by SANKET7738** [comment]
make sure you are on the main branch. then use the command `git fetch main-repo-url`  then followed by command `git pull main-repo-url`  .

**Pull request closed without merging**
