### PR TITLE
Caesar Cipher Technique 

### PR DESCRIPTION
**Pull request by Nagasuruthika**
Issue  #2 Implement Cesar Cipher 
"A script to implement Cesar Cipher in Python. the function should take a message and a shift value and should return the encrypted message."

### CODE REVIEW

**Comment by tejan-singh** [comment]
Please also add parent issue for review.

**Review by tejan-singh — CHANGES_REQUESTED** [review]
Please add relevant images to your folder to get them displayed in readme

**Comment by Nagasuruthika** [comment]
@tejan-singh I've added already added 2 images to the folder already.

**Comment by tejan-singh** [comment]
I cant see your images in the readme preview. Please check again.

**Comment by Nagasuruthika** [comment]
@tejan-singh can you see that two images have been uploaded in the files changed?

**Comment by yashaswibiyahut** [comment]
LGTM👍

**Review by yashaswibiyahut — APPROVED** [review]

**Pull request merged**
