### PR TITLE
Port-Scanner-Added

### PR DESCRIPTION
**Pull request by Ninjavin**
I have written a Python script for scanning ports of a server. Please review and suggest any necessary changes. Issue Number #8

### CODE REVIEW

**Review by tejan-singh — CHANGES_REQUESTED** [review]
please write requirement to run this script in the readme.

**Review by tejan-singh — CHANGES_REQUESTED** [review]
implement these inputs in port scanner like
 Press 1 for reserved ports
 Press 2 for all ports
 Press 3 for Critical ports
 Press 4 for manual ports

**Comment by Ninjavin** [comment]
I have made the required changes. Please review

**Comment by tejan-singh** [comment]
Nice work! @Ninjavin

**Pull request merged**
