### PR TITLE
Added the code in the required format for bulk LinkedIn request

### PR DESCRIPTION
**Pull request by Tejas1510**

### CODE REVIEW

**Comment by tejan-singh** [comment]
please mention the parent issue for reviewing.

**Comment by Tejas1510** [comment]
The parent issue is
Script for accepting bulk LinkedIn requests

**Comment by tejan-singh** [comment]
use "#" to mention the exact issue no. This way it's easy to review.

**Comment by Tejas1510** [comment]
@tejan-singh sorry for the inconvenience caused
The issue name is Script for accepting bulk LinkedIn requests and its issue no is #4

**Comment by tejan-singh** [comment]
@Tejas1510  As I already mentioned, Unassigned issues and PRs will be marked as invalid. You will not be scored for invalid PRs.

**Comment by Tejas1510** [comment]
@tejan-singh Sir you have merged my code 
So do I need to again raise a PR by asking to assign me

**Comment by Tejas1510** [comment]
Also, i was assigned issue #61 and I have raised a Pr can you please give it a look @tejan-singh Sir

**Pull request merged**
