### PR TITLE
Amazon price tracker #97

### PR DESCRIPTION
**Pull request by Namyalg**
Script to track the price of a product on Amazon added

Relates to #97

### CODE REVIEW

**Review by tejan-singh — CHANGES_REQUESTED** [review]
please specify all the requirements to run this script in the readme

**Comment by Namyalg** [comment]
I have added it

**Review by tejan-singh — CHANGES_REQUESTED** [review]
Please add all images to a seperate folder

**Comment by Namyalg** [comment]
Done

**Pull request merged**
