### PR TITLE
Created the Random Name Generator code having issue no #65

### PR DESCRIPTION
**Pull request by Tejas1510**
I have created the code for the Random Name generator having issue no #65.
The complete code is made with HTML, CSS, and Javascript.
There is a submit on the click of which a random name is generated.
Please give it a look

### CODE REVIEW

**Comment by tejan-singh** [comment]
Nice work @Tejas1510  but as I have mentioned earlier in our group, you have to ask to assign the particular issue to yourself. We are not accepting PRs which are not assigned.

**Comment by tejan-singh** [comment]
When a mentor or maintainer assigns you particular issue, then you work on it and send PR for review.

**Comment by Tejas1510** [comment]
@tejan-singh Sir can you assign me this issue

**Comment by yashaswibiyahut** [comment]
@Tejas1510  This issue is already assigned to someone else

**Comment by Tejas1510** [comment]
@yashaswibiyahut mam in the assignee's section it is showing no one assigned 
so I asked for it

**Comment by yashaswibiyahut** [comment]
@Tejas1510 kindly see it once it already assigned someone.

**Comment by Tejas1510** [comment]
ok mam @yashaswibiyahut 
If there is any opening on this issue, please let me know as I have made a code for this and would be happy to make a PR

**Pull request closed without merging**
