### PR TITLE
Substitution cipher 

### PR DESCRIPTION
**Pull request by Namyalg**
- Script for performing Substitution Cipher added
- The key is accepted as a CSV file

Relates to #3

### CODE REVIEW

**Comment by tejan-singh** [comment]
please attach a readme file explaining working and screenshots.

**Review by tejan-singh — CHANGES_REQUESTED** [review]
add readme for your code.
add your python file and your readme in a folder.

**Comment by yashaswibiyahut** [comment]
Please add an example/use case how to use this script in readme file
rest LGTM

**Review by yashaswibiyahut — CHANGES_REQUESTED** [review]
Please add an example/use case how to use this script in readme file.
rest LGTM

**Comment by Namyalg** [comment]
Okay, will add it

**Comment by Namyalg** [comment]
Example has been added

**Review by yashaswibiyahut — APPROVED** [review]
LGTM👍

**Pull request merged**
