### PR TITLE
Python script to shut down your System

### PR DESCRIPTION
**Pull request by Nagasuruthika**
Issue : a simple python script to shut down your System #14

### CODE REVIEW

**Comment by Nagasuruthika** [comment]
@SANKET7738 Is it fine now? Squashed the commits.

**Comment by SANKET7738** [comment]
just add all the images in a folder or you can use `Imgur` to refer to these endpoints.

**Comment by tejan-singh** [comment]
Hey! @Nagasuruthika. You have added a lot of images and its good. But they all need to be in a seperate images folder.

**Review by tejan-singh — CHANGES_REQUESTED** [review]
add images folder

**Comment by Nagasuruthika** [comment]
Changes made @tejan-singh @SANKET7738 can you please check?

**Pull request merged**
