### PR TITLE
Image to Text

### PR DESCRIPTION
**Pull request by Namyalg**
Script to store the text in an image to a text file added

Relates to #7

### CODE REVIEW

**Comment by tejan-singh** [comment]
please add a readme file describiing your code and send a pull request again.

**Comment by Namyalg** [comment]
Okay, will do!

**Review by tejan-singh — CHANGES_REQUESTED** [review]
add readme file to your code

**Comment by Namyalg** [comment]
I have added the README and made the changes

**Comment by yashaswibiyahut** [comment]
LGTM 👍

**Review by yashaswibiyahut — APPROVED** [review]

**Review by yashaswibiyahut — CHANGES_REQUESTED** [review]
Please add an example/use case how to use this script in readme file.
rest LGTM

**Comment by Namyalg** [comment]
Okay, will do add it

**Comment by Namyalg** [comment]
Example has been added

**Review by yashaswibiyahut — APPROVED** [review]
LGTM👍

**Pull request merged**
