### PR TITLE
Added program to get system information

### PR DESCRIPTION
**Pull request by harshareddy794**
Linked issue #25

### CODE REVIEW

**Comment by harshareddy794** [comment]
Please review my PR @yashaswibiyahut

**Comment by yashaswibiyahut** [comment]
@harshareddy794 Please add comments to your code.

**Review by yashaswibiyahut — CHANGES_REQUESTED** [review]
Add Comments

**Comment by harshareddy794** [comment]
@yashaswibiyahut Changes done

**Review by yashaswibiyahut — CHANGES_REQUESTED** [review]
@harshareddy794  Please add an example/use case of how to use this script in the readme file.
Rest LGTM.

**Comment by harshareddy794** [comment]
@yashaswibiyahut  I have added how to run script and output image also in readme

**Review by yashaswibiyahut — APPROVED** [review]

**Pull request merged**
